services:
  app:
    build: ./app
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://test:test@db/test
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - app-network
    

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
