- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Обновлять кэш, если он старше 1 часа


- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - pyhon3-pip
    state: present
    update_cache: no
    force_apt_get: yes

- name: Create directory for GPG keys
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG-key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add the repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: apt update again
  apt:
    update_cache: yes

- name: Install Docker and Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Check if Docker installed correctly
  command: docker run hello-world
  register: docker_hello_world
  ignore_errors: yes

- name: Display Output
  debug:
    var: docker_hello_world.stdout

- name: Check if Docker Compose installed correctly
  command: docker compose version
  register: compose_version
  ignore_errors: yes

- name: Display Output
  debug:
    var: compose_version.stdout


- name: Install Docker Python module
  pip:
    name: docker
    state: present
    executable: pip3
  
