- name: Deploy Application
  hosts: all
  become: yes
  vars:
    project_dir: "/home/github-runner/devop-blog-project"

  tasks:

    - name: Stop and remove old containers
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml down --rmi all --volumes
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: yes
  
    - name: Pull latest images
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml pull
      args:
        chdir: "{{ project_dir }}"


    - name: Build Dcoker images
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml build
      args:
        chdir: "{{ project_dir }}"
      register: build_result
      failed_when: build_result.rc != 0

        
    - name: Start containers
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ project_dir }}"
      register: up_result
      failed_when: up_result.rc != 0

    - name: Show container logs on failure
      command: docker compose -f {{ project_dir }}/docker-compose.yml logs
      args:
        chdir: "{{ project_dir }}"
      when: build_result.failed or up_result.failed
