- name: Deploy Application
  hosts: all
  become: yes
  vars:
    project_dir: "/home/github-runner/devop-blog-project"

  tasks:

    - name: Stop and remove old containers
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml down --rmi all --volumes
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: yes
  
    - name: Pull latest images
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml pull
      args:
        chdir: "{{ project_dir }}"
        
    - name: Ensure containers are running
      command: /usr/bin/docker compose -f {{ project_dir }}/docker-compose.yml up -d --build
      args:
        chdir: "{{ project_dir }}"
      register: compose_up_result.rc !=0

    - name: Show container logs on failure
      command: docker compose -f {{ project_dir }}/docker-compose.yml logs
      args:
        chdir: "{{ project_dir }}"
      when: compose_up_result.failed
