- name: Deploy Application
  hosts: all
  become: yes
  vars:
    project_dir: "{{ project_dir | default('/home/github-runner/devops-project') }}"
    compose_files:
      - "docker-compose.yml"
    
  tasks:
    - name: Validate Docker Compose v2
      shell: docker compose version --short
      register: docker_version
      changed_when: false
      failed_when:
        - "docker_version.rc != 0"
        - "not docker_version.stdout.startswith('2.')"

    - name: Fail if version < 2.x
      fail:
        msg: "Requires Docker Compose v2.x.x. Current version: {{ docker_version.stdout }}"
      when:
        - "docker_version.rc == 0"
        - "not docker_version.stdout.startswith('2.')"

    - name: Full cleanup of previous deployment
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "/usr/bin/docker compose"
        state: absent
        remove_volumes: yes
        remove_images: all
        timeout: 30
      ignore_errors: yes

    - name: Build and start services (up --build)
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "/usr/bin/docker compose"
        state: present
        build: always
        pull: never
        restart: always
        environment:
          DOCKERHUB_USERNAME: "{{ lookup('env', 'DOCKERHUB_USERNAME') | default('devopstestproject') }}"
          DB_USER: "{{ lookup('env', 'DB_USER') | default('test') }}"
          DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') | default('test') }}"
          DB_NAME: "{{ lookup('env', 'DB_NAME') | default('test') }}"

    - name: Health check services
      uri:
        url: http://localhost:8080
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: 5
      delay: 10

