- name: Deploy Application
  hosts: all
  become: yes
  vars:
    project_dir: "{{ project_dir | default('/home/github-runner/devops-project') }}"
    compose_files:
      - "docker-compose.yml"
    
  tasks:
    
    - name: Full cleanup of previous deployment
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "docker compose"
        state: absent
        remove_volumes: yes
        remove_images: all
        timeout: 30
      ignore_errors: yes

    - name: Build and start services (up --build)
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "docker compose"
        state: present
        build: always
        pull: never

    - name: Health check services
      uri:
        url: http://localhost:8080
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: 5
      delay: 10

