- name: Deploy Application
  hosts: all
  become: yes
  vars:
    compose_dir: "/home/github-runner/devop-blog-project"

  tasks:

    - name: Stop and remove old containers
      command: docker compose -f {{ compose_dir }}/docker-compose.yml down
      args:
        chdir: "{{ compose_dir }}"
      ignore_errors: yes
  
    - name: Pull latest images
      command: docker compose -f {{ compose_dir }}/docker-compose.yml pull
      args:
        chdir: "{{ compose_dir }}"
        
    - name: Ensure containers are running
      command: docker compose -f {{ compose_dir }}/docker-compose.yml up -d --build
      args:
        chdir: "{{ compose_dir }}"
