- name: Deploy Application
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Stop and remove old containers
      docker_compose:
        project_src: /home/github-runner/devop-blog-project
        files:
          - /home/github-runner/devop-blog-project
        state: absent
        remove_orphans: yes

  
    - name: Pull latest images
      docker_compose:
        project_src: /home/github-runner/devop-blog-project
        pull: yes
        files:
          - /home/github-runner/devop-blog-project/docker-compose.yml

    - name: Ensure containers are running
      docker_compose:
        project_src: /home/github-runner/devop-blog-project
        files:
          - /home/github-runner/devop-blog-project/docker-compose.yml
        state: present
        recreate: always # Force containers to rebuild everytime

