- name: Deploy Application
  hosts: all
  become: yes
  vars_files:
    - vars/secrets.yml # Enabling Encrypted file

  tasks:
    - name: Pull latest images
      docker_compose:
        project_src: /home/github-runner/devop-blog-project
        pull: yes
        files:
          - /home/github-runner/devop-blog-project/docker-compose.yml

    - name: Ensure containers are running
      docker_compose:
        project_src: /home/github-runner/devop-blog-project
        files:
          - /home/github-runner/devop-blog-project/docker-compose.yml
        state: present

