- name: Deploy Application
  hosts: all
  become: yes
  vars:
    project_dir: "{{ project_dir | default('/home/github-runner/devops-project') }}"
    compose_files:
      - "docker-compose.yml"
    
  tasks:
    - name: Validate Docker Compose v2
      shell: docker compose version --format json
      register: docker_version_json
      changed_when: false
      failed_when:
        - "docker_version_json.rc != 0"
        - "'v2' not in docker_version_json.stdout"

    - name: Fail if version < 2.x
      fail:
        msg: "Requires Docker Compose v2.x.x. Current version: {{ docker_version_json.stdout | from_json | json_query('version') }}"
      when: "'v2' not in docker_version_json.stdout"

    - name: Full cleanup of previous deployment
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "/usr/bin/docker-compose"
        state: absent
        remove_volumes: yes
        remove_images: all
        timeout: 30
      ignore_errors: yes

    - name: Build and start services (up --build)
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files: "{{ compose_files }}"
        docker_cli: "/usr/bin/docker-compose"
        state: present
        build: always
        pull: never

    - name: Health check services
      uri:
        url: http://localhost:8080
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: 5
      delay: 10

