name: CI/CD Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app/tests/


  build-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test Containers
        run: |
          docker-compose -f docker-compose.ci.yml up --build -d
          sleep 15 # Wait for containers to initialise
          curl --fail http://localhost:80
          curl --fail http://localhost:9090/metrics


  build-and-push:
    needs: [test, build-test]
    if: github.repository == 'memento-a25/jun-devops-project'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Flask App
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=$GITHUB_REPOSITORY_URL

      - name: Build and Push Postgres Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres-custom:latest
          labels: |
            org.opencontainers.image.source=$GITHUB_REPOSITORY_URL


  deploy:
    needs: [test, build-test, build-and-push]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via Ansible
        run: ansible-playbook ansible/deploy.yml
