name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning Repo
      uses: git clone https://github.com/jun-devops-project.git /root/devop-blog-project

    - name: Setup Python
      run: sudo apt-get install python3-pip python3-dev

    - name: Print Python Version
      run: python --version

    - name: Print Python3 Version
      run: python3 --version

    - name: Dockerfile check
      run: docker build -t test-flask-app /root/devop-blog-project/app/Docker /root/devop-blog-project/app

    - name: Container run
      run: docker run -d -p 5000:5000 test-flask-app

    - name: Deploying Infrastructure via Ansible
      run: ansible-playbook /root/devop-blog-project/ansible/playbook.yml

    - name: Deploying app via Ansible
      run: ansible-playbook /root/devop-blog-project/ansible/app_playbook.yml
